## Installing dependencies

RAG Pipeline:
document loading
embedded model
llm model
vector database

In [1]:
import sys
!python -m pip install pypdf sentence-transformers faiss-cpu torch huggingface_hub groq langsmith python-dotenv tiktoken

print('\nInstallation completed')

Requirement already satisfied: pypdf in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (6.18.1)
Requirement already satisfied: sentence-transformers in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (6.0.1)
Requirement already satisfied: faiss-cpu in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.15.0)
Requirement already satisfied: torch in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (2.14.0)
Requirement already satisfied: huggingface_hub in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.31.0)
Requirement already satisfied: groq in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (0.37.1)
Requirement already satisfied: langsmith in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (0.12.4)
Requirement already satisfied: python-dotenv in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.2.3)
Requirement already satisfied: tiktoken in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (0.14.0)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sentence-transformers) (5.17.0)
Requirement already satisfied: tokenizers>=0.19 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sentence-transformers) (0.23.2)
Requirement already satisfied: numpy>=1.24.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sentence-transformers) (2.5.3)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sentence-transformers) (1.9.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sentence-transformers) (1.18.1)
Requirement already satisfied: typing_extensions>=4.10.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sentence-transformers) (4.70.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (3.32.6)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (26.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: anyio in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.15.1)
Requirement already satisfied: certifi in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: regex>=2025.10.22 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2026.9.10)
Requirement already satisfied: typer in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from torch) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from groq) (1.9.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from groq) (2.13.5)
Requirement already satisfied: sniffio in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from groq) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic<3,>=1.9.0->groq) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic<3,>=1.9.0->groq) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic<3,>=1.9.0->groq) (0.4.4)
Requirement already satisfied: httpx2<3,>=2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (2.13.0)
Requirement already satisfied: orjson>=3.9.14 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (2.34.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (0.17.1)
Requirement already satisfied: websockets>=15.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (16.1.1)
Requirement already satisfied: xxhash>=3.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (0.25.0)
Requirement already satisfied: httpcore2==2.13.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx2<3,>=2->langsmith) (2.13.0)
Requirement already satisfied: truststore>=0.10 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx2<3,>=2->langsmith) (0.10.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from requests>=2.0.0->langsmith) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from requests>=2.0.0->langsmith) (2.7.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from joblib>=1.4.0->scikit-learn>=1.1.0->sentence-transformers) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.1.2)

Installation completed

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
print("Installing Dependencies")

import sys
!python -m pip install langchain langchain-community langchain-text-splitters langchain-huggingface langchain-groq langchain-google-genai langchain-openai langchain-core faiss-cpu pypdf sentence-transformers transformers torch huggingface_hub groq langsmith python-dotenv tiktoken


print('\nInstallation completed')

Installing Dependencies
Requirement already satisfied: langchain in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.4.0)
Requirement already satisfied: langchain-community in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (0.4.2)
Requirement already satisfied: langchain-text-splitters in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.1.2)
Requirement already satisfied: langchain-huggingface in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.2.2)
Requirement already satisfied: langchain-groq in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.1.3)
Requirement already satisfied: langchain-google-genai in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (4.4.0)
Requirement already satisfied: langchain-openai in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.6.2)
Requirement already satisfied: langchain-core in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.6.3)
Requirement already satisfied: faiss-cpu in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.15.0)
Requirement already satisfied: pypdf in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (6.18.1)
Requirement already satisfied: sentence-transformers in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (6.0.1)
Requirement already satisfied: transformers in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (5.17.0)
Requirement already satisfied: torch in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (2.14.0)
Requirement already satisfied: huggingface_hub in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.31.0)
Requirement already satisfied: groq in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (0.37.1)
Requirement already satisfied: langsmith in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (0.12.4)
Requirement already satisfied: python-dotenv in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.2.3)
Requirement already satisfied: tiktoken in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (0.14.0)
Requirement already satisfied: langgraph<1.3.0,>=1.2.11 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain) (1.2.11)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain) (2.13.5)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (0.0.19)
Requirement already satisfied: packaging>=23.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (26.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (0.17.1)
Requirement already satisfied: anyio>=3.5.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (4.15.1)
Requirement already satisfied: distro>=1.7.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (2.13.0)
Requirement already satisfied: orjson>=3.9.14 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (1.3.1)
Requirement already satisfied: websockets>=15.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (16.1.1)
Requirement already satisfied: xxhash>=3.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith) (0.25.0)
Requirement already satisfied: certifi in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (1.0.9)
Requirement already satisfied: idna in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core) (0.16.0)
Requirement already satisfied: httpcore2==2.13.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx2<3,>=2->langsmith) (2.13.0)
Requirement already satisfied: truststore>=0.10 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx2<3,>=2->langsmith) (0.10.4)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (4.2.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langgraph<1.3.0,>=1.2.11->langchain) (0.4.4)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain) (1.12.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.4)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (3.14.3)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (1.0.8)
Requirement already satisfied: numpy>=2.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (2.5.3)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (2.15.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (2.0.53)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.8.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from requests>=2.0.0->langsmith) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from requests>=2.0.0->langsmith) (2.7.0)
Requirement already satisfied: greenlet>=1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.6)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-huggingface) (0.23.2)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (3.32.6)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (1.6.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface_hub) (4.70.1)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-google-genai) (1.2.0)
Requirement already satisfied: google-genai<3.0.0,>=2.20.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-google-genai) (2.23.0)
Requirement already satisfied: google-auth<3.0.0,>=2.56.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (2.58.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (50.0.1)
Requirement already satisfied: openai<4.0.0,>=2.45.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-openai) (3.14.0)
Requirement already satisfied: regex in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from tiktoken) (2026.9.10)
Requirement already satisfied: jiter<1,>=0.16.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from openai<4.0.0,>=2.45.0->langchain-openai) (0.17.0)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sentence-transformers) (1.9.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sentence-transformers) (1.18.1)
Requirement already satisfied: typer in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from transformers) (0.8.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from torch) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: cffi>=2.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (2.1.1)
Requirement already satisfied: pycparser in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai<3.0.0,>=2.20.0->langchain-google-genai) (0.6.4)
Requirement already satisfied: joblib>=1.4.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from joblib>=1.4.0->scikit-learn>=1.1.0->sentence-transformers) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

Installation completed

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
LLM_Provider = 'groq'
LLM_Model = 'openai/gpt-oss-20b'
CORPUS_PATH = "./zyro-dynamics-hr-corpus"

In [4]:
%pip install langchain-community langchain-core langchain-text-splitters langchain-chroma pypdf

Requirement already satisfied: langchain-community in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (0.4.2)
Requirement already satisfied: langchain-core in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.6.3)
Requirement already satisfied: langchain-text-splitters in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.1.2)
Requirement already satisfied: langchain-chroma in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (1.1.0)
Requirement already satisfied: pypdf in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (6.18.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (3.14.3)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (1.0.8)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (0.12.4)
Requirement already satisfied: numpy>=2.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (2.5.3)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (2.15.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (2.34.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (2.0.53)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-community) (9.1.4)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (0.0.19)
Requirement already satisfied: packaging>=23.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (26.3)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (2.13.5)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (4.16.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-core) (0.17.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.8.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.5)
Requirement already satisfied: anyio in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (4.15.1)
Requirement already satisfied: certifi in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (1.0.9)
Requirement already satisfied: idna in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core) (3.19)
Requirement already satisfied: h11>=0.16 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.1.1)
Requirement already satisfied: distro>=1.7.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.9.0)
Requirement already satisfied: httpx2<3,>=2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (2.13.0)
Requirement already satisfied: orjson>=3.9.14 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.12.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Requirement already satisfied: websockets>=15.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (16.1.1)
Requirement already satisfied: xxhash>=3.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (4.0.1)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: httpcore2==2.13.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.1.125->langchain-community) (2.13.0)
Requirement already satisfied: truststore>=0.10 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.1.125->langchain-community) (0.10.4)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core) (0.4.4)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.7.0)
Requirement already satisfied: greenlet>=1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.6)
Requirement already satisfied: chromadb<2.0.0,>=1.3.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from langchain-chroma) (1.5.9)
Requirement already satisfied: build>=1.0.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.6.1)
Requirement already satisfied: pybase64>=1.4.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.5.0)
Requirement already satisfied: uvicorn>=0.18.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.53.0)
Requirement already satisfied: onnxruntime>=1.14.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.30.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.44.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.44.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.44.0)
Requirement already satisfied: tokenizers>=0.13.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.23.2)
Requirement already satisfied: pypika>=0.48.9 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.70.1)
Requirement already satisfied: overrides>=7.3.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (7.7.0)
Requirement already satisfied: importlib-resources in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.84.0)
Requirement already satisfied: bcrypt>=4.0.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.27.2)
Requirement already satisfied: kubernetes>=28.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (36.0.3)
Requirement already satisfied: mmh3>=4.0.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (5.3.0)
Requirement already satisfied: rich>=10.11.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (15.0.0)
Requirement already satisfied: jsonschema>=4.19.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.26.0)
Requirement already satisfied: pyproject_hooks in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from build>=1.0.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.2.0)
Requirement already satisfied: colorama in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from build>=1.0.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.4.6)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jsonschema>=4.19.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2026.6.3)
Requirement already satisfied: six>=1.9.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.9.2)
Requirement already satisfied: requests-oauthlib in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.0.0)
Requirement already satisfied: durationpy>=0.7 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from kubernetes>=28.1.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.11)
Requirement already satisfied: flatbuffers in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from onnxruntime>=1.14.1->chromadb<2.0.0,>=1.3.5->langchain-chroma) (7.36.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.75.3)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.44.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.44.0)
Requirement already satisfied: opentelemetry-proto==1.44.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.44.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.65b0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from opentelemetry-sdk>=1.2.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.65b0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.1.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.31.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (3.32.6)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.6.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from typer>=0.9.0->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.0.5)
Requirement already satisfied: httptools>=0.8.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb<2.0.0,>=1.3.5->langchain-chroma) (0.8.0)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import os
from dotenv import load_dotenv
print("Did it find the .env file?:",load_dotenv())
if os.getenv("GROQ_API_KEY"):
    print("GROQ api key is imported..")
else:
    print("GROQ api key is not imported")
from langchain_community.document_loaders import PyPDFDirectoryLoader 
from langchain_text_splitters import RecursiveCharacterTextSplitter

Did it find the .env file?: True
GROQ api key is imported..

C:\Users\ABHINANDH UNNI\AppData\Local\Temp\ipykernel_23548\3242123715.py:8: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFDirectoryLoader
c:\Users\ABHINANDH UNNI\OneDrive\Desktop\Intelligent Rag Bot\.venv-1\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
loader=PyPDFDirectoryLoader(CORPUS_PATH)
documents=loader.load()
print(f"loaded {len(documents)} documents")

loaded 39 documents

In [7]:
splitter = RecursiveCharacterTextSplitter(
chunk_size=800,
chunk_overlap=100
)

chunks=splitter.split_documents(documents)
print(f"Created {len(chunks)} chunks")

Created 107 chunks

In [8]:
from langchain_huggingface import HuggingFaceEmbeddings

model=HuggingFaceEmbeddings(
    model_name='sentence-transformers/all-MiniLM-L6-v2'
)
print("Embedded done")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1614.99it/s]

Embedded done

In [9]:
from langchain_community.vectorstores import FAISS 
vectorstore = FAISS.from_documents(chunks,model)

retriever = vectorstore.as_retriever(search_kwargs ={"k":3})
print("Done!..")

Done!..

In [10]:
from langchain_groq import ChatGroq 
llm_model = ChatGroq(
    model=LLM_Model,
    groq_api_key=os.getenv("GROQ_API_KEY"),
    temperature=0.6,
    max_tokens=500
)

print("LLM model groq initialsed")

LLM model groq initialsed

In [11]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langsmith import traceable
RAG_PROMPT= ChatPromptTemplate.from_template(
""" 
You are an HR assistant.Your goal is to accurately answer the employee questions using ONLY the provided context below.
context;{context}
question:{question}
"""
)

def format_docs(docs):
    return ".\n\n".join(d.page_content for d in docs)

@traceable(name="rag_chain")

def rag_chain(question : str):
    docs=retriever.invoke(question)
    context=format_docs(docs)
    chain=RAG_PROMPT | llm_model | StrOutputParser()
    answer=chain.invoke({"context":context,"question":question})
    return {"answer":answer}

In [12]:
rag_chain("What is the code of conduct?")

{'answer': '**Zyro Dynamics Pvt. Ltd. – Code of Conduct (Doc Code: ZDL‑HR‑004)**  \n\nThe Code of Conduct is a company‑wide policy that sets the standards for how all employees, contractors, consultants, and interns are expected to behave. It is a formal, internal document (Version\u202fV.02, effective\u202f01\u202fJanuary\u202f2025) owned by the Legal, Compliance and HR Department.  \n\nKey elements of the Code include:  \n\n| Section | What it covers | Main points |\n|---------|----------------|-------------|\n| **Introduction** | Purpose and commitment | Zyro Dynamics pledges honesty, integrity, and professionalism. The Code is a fundamental condition of employment, and all new hires must read, understand, and acknowledge it. |\n| **Scope & Applicability** | Who it applies to | All individuals employed by or associated with Zyro Dynamics, regardless of employment type (full‑time, part‑time, contract, internship). It covers behaviour at the workplace, client sites, official travel, company events, and any digital or social media interaction linked to the company. |\n| **Professional Conduct – Workplace Behaviour** | Day‑to‑day expectations | • Treat colleagues, clients, vendors, and visitors with dignity and respect (regardless of designation, gender, age, religion, nationality, sexual orientation, or disability).  <br>• Maintain a professional tone and language in all communications (verbal, written, electronic, in‑person).  <br>• Resolve workplace disagreements through respectful dialogue; if unresolved, involve the reporting manager or HR.  <br>• Avoid offensive or discriminatory language, inappropriate content'}

In [13]:
GUARDIAL_PROMPT=ChatPromptTemplate.from_template("""
You are a scope classifier for an HR assistant.Decide whether the question below is something an HR assistant should answer (company leave policy,
reimbursement,code of conduct,or other internal HR topics) or something out of scope (general knowledge,coding help,unrelated small talk,etc).
Respond with exactly one word: IN_SCOPE or OUT_OF_SCOPE.
Question: {question}"""
)
REFUSAL_MESSAGE = (
    "I'm an HR assistant and can only help with questions about company HR "
    "policies (leave,reimbursement,code of conduct,etc.).I don't have "
    "information to answer that question."
)

In [14]:
def ask_bot(question:str):
    guardial_chain=GUARDIAL_PROMPT | llm_model | StrOutputParser()
    verdict= guardial_chain.invoke({"question" : question}).strip().upper()
    if "OUT_OF_SCOPE" in verdict or verdict != "IN_SCOPE":
        return {"answer" : REFUSAL_MESSAGE , "sources" : [ ]}
    return rag_chain(question)

print("Guardial Initialised")

Guardial Initialised

In [15]:
test_question=["How many casual leaves do i get per year?",
"What is the internet reimbursement limit?",
"What is the capital of France?"]

for i,q in enumerate(test_question,1):
    result=ask_bot(q)
    print(f"Q{i}: {q}")
    print(f"A{i}: {result['answer']}")
    sources=result.get("sources")
    if sources:
        print(
            f"Sources: "
            f"{[d.metadata.get('source') for d in result['sources']]}"
        )
    print("-" * 60)

Q1: How many casual leaves do i get per year?
A1: I’m sorry, but the policy details you shared don’t specify the exact number of casual leaves an employee is entitled to per year. If you need that information, it would be best to check the company’s leave policy handbook or contact HR directly.
------------------------------------------------------------
Q2: What is the internet reimbursement limit?
A2: The internet reimbursement limit is **Rs. 1,000 per month** for full‑remote employees at level 5 and above.
------------------------------------------------------------
Q3: What is the capital of France?
A3: I'm an HR assistant and can only help with questions about company HR policies (leave,reimbursement,code of conduct,etc.).I don't have information to answer that question.
------------------------------------------------------------

In [16]:
pip install pandas ipykernel

Requirement already satisfied: pandas in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (3.0.6)
Requirement already satisfied: ipykernel in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (7.3.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: comm>=0.1.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (9.17.1)
Requirement already satisfied: jupyter-client>=8.9.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (8.10.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (1.7.2)
Requirement already satisfied: packaging>=22 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (26.3)
Requirement already satisfied: psutil>=5.7 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (27.2.0)
Requirement already satisfied: tornado>=6.4.1 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (6.5.9)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipykernel) (5.16.1)
Requirement already satisfied: colorama>=0.4.4 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.53)
Requirement already satisfied: pygments>=2.14.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipython>=7.23.1->ipykernel) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.8.3)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: typing-extensions>=4.13.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jupyter-client>=8.9.0->ipykernel) (4.16.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.11.8)
Requirement already satisfied: six>=1.5 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.2)
Requirement already satisfied: pure-eval in c:\users\abhinandh unni\onedrive\desktop\intelligent rag bot\.venv-1\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.4)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import pandas as pd 
test_df=pd.read_csv("test (1).csv")
test_df

   question_id                                           question
0          Q01       How does my Earned Leave accrue every month?
1          Q02  How much Earned Leave can I carry forward to n...
2          Q03  How many weeks of Maternity Leave am I entitle...
3          Q04    Do I need a medical certificate for sick leave?
4          Q05  What date does my salary get credited every mo...
5          Q06  What's the salary range for an L4 Senior emplo...
6          Q07  What medical insurance coverage does the compa...
7          Q08   When am I put on a Performance Improvement Plan?
8          Q09  What's the timeline for the Annual Performance...
9          Q10       Am I eligible to work from home at my grade?
10         Q11       Can I accept a gift from a client or vendor?
11         Q12   What are the password rules for company systems?
12         Q13  How do I raise a POSH complaint and what's the...
13         Q14  How much notice period do I need to serve to r...
14         Q15  What's my hotel and daily allowance for intern...
15         Q16  How do I apply for a job opening at Zyro Dynam...
16         Q17          Can you tell me my ESOP vesting schedule?
17         Q18         What was Zyro Dynamics' revenue last year?
18         Q19            How does ZyroCRM compare to Salesforce?
19         Q20                  What is Zoho's leave policy like?

In [18]:
answers=[]
for i,row in test_df.iterrows():
    q=row["question"]
    result=ask_bot(q)
    answers.append(result["answer"])
    print(f"[{i+1}/{len(test_df)}] {q}\n-> {result['answer']}\n{'-'*60}")

[1/20] How does my Earned Leave accrue every month?
-> Earned Leave (EL) is added to your balance on a monthly basis as follows:

| Status | Monthly accrual rate | Eligibility note |
|--------|----------------------|------------------|
| **After you’ve completed 1 year of continuous service** | **1.25 days per month** | You must have worked at least 240 days in that year to qualify for the initial 15‑day balance, after which the 1.25‑day/month rate applies. |
| **During probation** | **0.5 days per month** | These days accrue while you’re on probation and become usable only once you’re confirmed. |

So, once you’re fully eligible (post‑probation, one year of service), you earn **1.25 days of EL each month**. If you’re still on probation, you earn **0.5 days per month** until confirmation.
------------------------------------------------------------
[2/20] How much Earned Leave can I carry forward to next year?
-> According to the policy details provided, there is no stated limit on carrying earned leave (EL) into the next financial year. The rule that prevents carry‑forward applies only to Casual Leave and Sick Leave. Therefore, you can carry forward your earned leave balance into the next year, subject to any additional company‑specific rules that may not be included in the excerpt you shared.
------------------------------------------------------------
[3/20] How many weeks of Maternity Leave am I entitled to?
-> You are entitled to **26 weeks of paid maternity leave** for each of your first two live births.
For a third child, the entitlement reduces to **12 weeks**.

Additionally, you may take up to **8 weeks of pre‑natal leave** before the expected delivery date.
------------------------------------------------------------
[4/20] Do I need a medical certificate for sick leave?
-> Yes.
According to the policy, if your sick leave is **more than 2 consecutive days**, you must provide a Medical Certificate from a registered medical practitioner. The certificate must be submitted within 3 working days after you return to work. For 2 or fewer consecutive days of sick leave, a medical certificate is not required.
------------------------------------------------------------
[5/20] What date does my salary get credited every month?
-> Your salary is credited to your registered bank account by the **7th of the following month**. If there are any changes to this payment date, the Payroll team will inform you in advance.
------------------------------------------------------------
[6/20] What's the salary range for an L4 Senior employee?
-> The salary range for an **L4 Senior** employee is **Rs. 16.0 L to Rs. 26.0 L per annum**.
------------------------------------------------------------
[7/20] What medical insurance coverage does the company provide?
-> The company provides a **Group Medical Insurance** that covers you, your spouse, and up to two dependent children for **up to ₹5,00,000 per year**. All premiums for this coverage are fully paid by the company.
------------------------------------------------------------
[8/20] When am I put on a Performance Improvement Plan?
-> You will be placed on a Performance Improvement Plan (PIP) if you receive a rating of **1 (Does Not Meet Expectations) or 2 (Partially Meets Expectations) in two consecutive review cycles**.
------------------------------------------------------------
[9/20] What's the timeline for the Annual Performance Review?
-> The Annual Performance Review (APR) is conducted once a year, scheduled for **March** each year.
------------------------------------------------------------
[10/20] Am I eligible to work from home at my grade?
-> **Answer:**

- If you are a **permanent employee at grade L3 or higher**, you are automatically eligible to work from home (WFH) under the company policy.

- If you are at **grade L1 or L2**, **on probation**, or **deployed at a client site**, you are **not** eligible for WFH unless you receive **written approval from the HR Director on a case‑by‑case basis**.

So, check your current grade and employment status. If you’re L3+ and permanent, you can work from home. If you’re below that, you’ll need HR approval to do so.
------------------------------------------------------------
[11/20] Can I accept a gift from a client or vendor?
-> **Answer**

According to Zyro Dynamics’ “GIFTS AND HOSPITALITY” policy:

| Gift | Can you accept it? | What to do |
|------|--------------------|------------|
| **Gift under Rs. 1,000** | **Yes** | Declare it to your reporting manager. |
| **Gift over Rs. 1,000** | **No** | Politely decline or surrender it to HR. |
| **Cash from any party** | **Never** | Immediate disciplinary action – you cannot accept cash. |

So you may accept a client or vendor gift only if its value is **below Rs. 1,000** and you must inform your manager. Gifts above that amount must be declined or handed over to HR.
------------------------------------------------------------
[12/20] What are the password rules for company systems?
-> I'm an HR assistant and can only help with questions about company HR policies (leave,reimbursement,code of conduct,etc.).I don't have information to answer that question.
------------------------------------------------------------
[13/20] How do I raise a POSH complaint and what's the timeline?
-> **How to raise a POSH complaint**

1. **Submit a written complaint**
   * Send a written complaint to the Internal Complaints Committee (ICC) by email or sealed letter.
   * Do this **within 3 months** of the incident (or the last incident in a series).

2. **ICC acknowledgement**
   * The ICC will acknowledge receipt and forward a copy to the respondent **within 7 working days**.

3. **Respondent’s reply**
   * The respondent will be given **10 working days** to submit a written response.

4. **ICC inquiry**
   * The ICC will conduct an inquiry, holding hearings for both parties and witnesses. (This follows the respondent’s reply.)

**Timeline summary**

| Step | Action | Timeframe |
|------|--------|-----------|
| 1 | Aggrieved person files complaint | ≤ 3 months from incident |
| 2 | ICC acknowledges & forwards to respondent | Within 7 working days |
| 3 | Respondent submits written response | Within 10 working days |
| 4 | ICC conducts inquiry | After step 3 |

*If you need more time, the ICC may extend the 3‑month filing period by an additional 3 months upon a
------------------------------------------------------------
[14/20] How much notice period do I need to serve to resign?
-> The notice period you need to serve when resigning depends on your current grade level. Below is the notice period schedule that applies:

| Grade | Notice Period | Notice Period Buyout |
|-------|---------------|----------------------|
| L1 to L3 | 30 days | Not available |
| L4 to L6 | 60 days | Available at the Company’s discretion |
| L7 to L9 | 90 days | Available at the Company’s discretion |
| L10 (C‑Suite) | 90 days | As per individual employment contract |

**How to submit your notice**

1. **Written notice** must be given to both your reporting manager and HR.
2. Submit the notice through the **ZyroHR portal**.
3. HR will confirm receipt of your notice in writing.

If you let us know your grade, we can confirm the exact notice period you are required to serve.
------------------------------------------------------------
[15/20] What's my hotel and daily allowance for international travel?
-> For international travel, the hotel per‑night rate and daily allowance are set by employee grade (in USD).
| Grade | Hotel per Night (USD) | Daily Allowance (USD) |
|-------|-----------------------|-----------------------|
| L3‑L4 | 120 | 60 |
| L5‑L6 | 180 | 90 |
| L7‑L8 | 220 | 120 |
| L9‑L10 | 350 | 200 |

Please refer to the table above and use the figures that correspond to your grade.
------------------------------------------------------------
[16/20] How do I apply for a job opening at Zyro Dynamics?
-> I'm an HR assistant and can only help with questions about company HR policies (leave,reimbursement,code of conduct,etc.).I don't have information to answer that question.
------------------------------------------------------------
[17/20] Can you tell me my ESOP vesting schedule?
-> Your ESOP follows a **4‑year vesting schedule with a 1‑year cliff**.
That means you’ll receive 25 % of your options after the first year, and the remaining 75 % will vest in equal portions over the next three years. This schedule applies to employees at grade **L5 and above**.
------------------------------------------------------------
[18/20] What was Zyro Dynamics' revenue last year?
-> I'm an HR assistant and can only help with questions about company HR policies (leave,reimbursement,code of conduct,etc.).I don't have information to answer that question.
------------------------------------------------------------
[19/20] How does ZyroCRM compare to Salesforce?
-> I'm an HR assistant and can only help with questions about company HR policies (leave,reimbursement,code of conduct,etc.).I don't have information to answer that question.
------------------------------------------------------------
[20/20] What is Zoho's leave policy like?
-> I’m sorry, but I only have information about Zyro Dynamics’ leave policy. I don’t have any details about Zoho’s leave policy.
------------------------------------------------------------

In [19]:
test_df["answer"]=answers
submission=test_df[["question_id","answer"]]
submission.to_csv("submission.csv",index=False)
submission.head()

  question_id                                             answer
0         Q01  Earned Leave (EL) is added to your balance on ...
1         Q02  According to the policy details provided, ther...
2         Q03  You are entitled to **26 weeks of paid materni...
3         Q04  Yes.  \nAccording to the policy, if your sick ...
4         Q05  Your salary is credited to your registered ban...